### ISSUE TITLE
Skudonet CE 7.0.1  apt-update issue fresh install

### ISSUE THREAD

**Issue by itxworks** [SKUDONET/skdlb#4] opened 2024-02-01 18:21 UTC
Hello,

on  a fresh install und thereafter an apt-upgrade - it ends in an unusable appliance ...
---
apt-get reinstall  skudonet
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 skudonet : Depends: nftables (< 1.0.0-8.0.0) but 1.0.6-2+deb12u2 is to be installed
E: Unable to correct problems, you have held broken packages.
--- 

Thank you.

**Comment by heig** [comment] 2024-02-08 12:40
Same issue over here...

**Comment by drsbaitso** [comment] 2024-04-20 19:11
Make sure you're on deb bookworm.

**Comment by itxworks** [comment] 2024-04-22 07:30
Seriously?

By using the ISO  installer its allready configured.
```
Linux nfnlblv33 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-1 (2023-07-14) x86_64
  _____ _  ___    _ _____   ____  _   _ ______ _______
 / ____| |/ / |  | |  __ \ / __ \| \ | |  ____|__   __|
| (___ | ' /| |  | | |  | | |  | |  \| | |__     | |
 \___ \|  < | |  | | |  | | |  | | . ` |  __|    | |
 ____) | . \| |__| | |__| | |__| | |\  | |____   | |
|_____/|_|\_\\____/|_____/ \____/|_| \_|______|  |_|

SKUDONET Community Edition
Software developed by Skudonet SL

If you want community support contact
        skudonet-ce-users@skudonet.com

or if need professional support open a ticket at
        https://central.skudonet.com/

Get information about our support services visiting
        https://www.skudonet.com/support/

Last login: Mon Apr 22 09:17:35 2024 from xxx.xxx.xxx.xx
```
```
cat /etc/apt/sources.list
deb http://deb.debian.org/debian/ bookworm main non-free-firmware
deb http://deb.debian.org/debian-security/ bookworm-security main non-free-firmware

# This system was installed using small removable media
# (e.g. netinst, live or single CD). The matching "deb cdrom"
# entries were disabled at the end of the installation process.
# For information about how to configure apt package sources,
# see the sources.list(5) manual.
```
Setting nftables on hold  for now ... looking forward for an real answer ...

**Comment by emiliocamposmartin** [comment] 2024-04-25 17:52
Hi, the SKUDONET ISO image fixes this problem, the issue is related with Debian nftables dependencies. Please install SKUDONET ISO instead. 

Thanks!

**Comment by itxworks** [comment] 2024-04-25 17:57
Hello, this issue is related to the latest SKUDONET CE ISO ... so far

**Comment by emiliocamposmartin** [comment] 2024-04-26 07:17
Hi, I can reproduce the problem, the nftables package included in Debian uninstalls skudonet and skudonet-gui-core in SKUDONET CE v.7.0.1. 

We are currently working on the new SKUDONET V.7 version, with many new features, we will check the dependencies. 

The problem is because SKUDONET CE v7.0.1 depends of our compiled nftables package. We will work to try to stop maintaining our package and use the nftables package included in the Bookworm instead. 

Thanks for the reports, We will keep this issue open until we implement the solution.

Emilio.

**Comment by itxworks** [comment] 2024-04-26 07:27
Hi Emilio,

thank you for the update  looking forward for this .

within l4xnat  is there a way to expire/delete  persistent sessions from the session db - via api call or something else ... thank you 

;-)

**Comment by dev-team-skudonet** [comment] 2024-06-19 12:02
Hi @itxworks, internally is supported as this is done at the moment a backend fails or a backend is moved to maintenance but the skudonet API doesn't expose this particular call.

**Comment by dev-team-skudonet** [comment] 2024-06-19 17:35
HI, SKUDONET 7.1.0 has been updated, this issue should be solved as we have fixed all the packages depdencies integrating the SKUDONET packages with Debian bookworm, you can read more about our time line here:

https://www.skudonet.com/about-us/timeline/

Refer to: [system] fixed nftables package dependency

Thanks for reporting this issue, we will proceed to close it

**Closed as completed by dev-team-skudonet** 2024-06-19 17:35 UTC
